package ventanas;

import clases.MetodosBarraLateral;
import clases.MetodosBarraMenu;
import clases.MetodosPaneles;
import java.sql.Connection;
import java.awt.Color;

/**
 *
 * @author ecpau
 */
public class MenuAdminForm extends javax.swing.JFrame {
    
    // Instancia de la conexion que se pasa del login al menu
    private Connection cn;
    
    // Instancia de la clase para añadir funcionalidad a los botones de la barra de título
    MetodosBarraMenu mbm = new MetodosBarraMenu();
    
    // Instancia de la clase para añadir funcionalidad a la barra lateral
    MetodosBarraLateral mbl = new MetodosBarraLateral();
    
    // Instancia de la clase para manipular la visibilidad de los paneles
    MetodosPaneles mp = new MetodosPaneles();
    
    // Variable para almacenar las coordenadas del mouse, se usa para calcular la posicion al arrastrar la ventana
    int mouseX, mouseY;
    
    /**
     * Crea una nueva instancia del formulario MenuAdminForm.
     *
     * @param cn La conexión a la base de datos que se utilizará en el formulario.
     */
    public MenuAdminForm(Connection cn) {
        // Asigna la conexión a la base de datos al atributo de la clase
        this.cn = cn;
        
        // Inicializa los componentes del formulario
        initComponents();
        
        // Oculta los paneles de la ventana de paneles y muestra el panel del menú principal
        mp.ocultarPaneles(panelVentanaPaneles);
        panelMenuPrincipal.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraTitulo = new javax.swing.JPanel();
        botonesBarraTitulo = new javax.swing.JPanel();
        contOcultar = new javax.swing.JPanel();
        lblOcultar = new javax.swing.JLabel();
        contMaximizar = new javax.swing.JPanel();
        lblMaximizar = new javax.swing.JLabel();
        contCerrar = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JLabel();
        barraLateral = new javax.swing.JPanel();
        contBarraLateral = new javax.swing.JPanel();
        contBotonBarraLateral = new javax.swing.JPanel();
        lblBotonBarraLateral = new javax.swing.JLabel();
        contConfiguracion = new javax.swing.JPanel();
        lblConfiguracion = new javax.swing.JLabel();
        contCerrarSesion = new javax.swing.JPanel();
        lblCerrarSesion = new javax.swing.JLabel();
        panelFondo = new javax.swing.JPanel();
        panelVentana = new javax.swing.JPanel();
        panelBarraLateral = new javax.swing.JLayeredPane();
        botonProductos = new javax.swing.JPanel();
        labelProductos = new javax.swing.JLabel();
        iconoProductos = new javax.swing.JLabel();
        botonUsuarios = new javax.swing.JPanel();
        iconoUsuarios = new javax.swing.JLabel();
        labelUsuarios = new javax.swing.JLabel();
        botonDescuentos = new javax.swing.JPanel();
        labelDescuentos = new javax.swing.JLabel();
        iconoDescuentos = new javax.swing.JLabel();
        botonVentas = new javax.swing.JPanel();
        iconoVentas = new javax.swing.JLabel();
        labelVentas = new javax.swing.JLabel();
        botonInformes = new javax.swing.JPanel();
        iconoInformes = new javax.swing.JLabel();
        labelInformes = new javax.swing.JLabel();
        botonCaja = new javax.swing.JPanel();
        labelCaja = new javax.swing.JLabel();
        iconoCaja = new javax.swing.JLabel();
        panelVentanaPaneles = new javax.swing.JPanel();
        panelMenuPrincipal = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        panelVentas = new javax.swing.JLayeredPane();
        panelProductos = new javax.swing.JLayeredPane();
        panelDescuentos = new javax.swing.JLayeredPane();
        panelUsuarios = new javax.swing.JLayeredPane();
        panelInformes = new javax.swing.JLayeredPane();
        panelCaja = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        barraTitulo.setBackground(new java.awt.Color(87, 154, 233));
        barraTitulo.setPreferredSize(new java.awt.Dimension(1280, 50));
        barraTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraTituloMouseDragged(evt);
            }
        });
        barraTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barraTituloMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraTituloMousePressed(evt);
            }
        });
        barraTitulo.setLayout(new java.awt.BorderLayout());

        botonesBarraTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contOcultar.setBackground(new java.awt.Color(87, 154, 233));
        contOcultar.setLayout(new java.awt.BorderLayout());

        lblOcultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickcheck/assets/barra_titulo/icons8-minimize-20-white.png"))); // NOI18N
        lblOcultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOcultarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOcultarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOcultarMouseExited(evt);
            }
        });
        contOcultar.add(lblOcultar, java.awt.BorderLayout.CENTER);

        botonesBarraTitulo.add(contOcultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        contMaximizar.setBackground(new java.awt.Color(87, 154, 233));
        contMaximizar.setLayout(new java.awt.BorderLayout());

        lblMaximizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickcheck/assets/barra_titulo/icons8-rectangle-20-white.png"))); // NOI18N
        lblMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMaximizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMaximizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMaximizarMouseExited(evt);
            }
        });
        contMaximizar.add(lblMaximizar, java.awt.BorderLayout.CENTER);

        botonesBarraTitulo.add(contMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 50));

        contCerrar.setBackground(new java.awt.Color(87, 154, 233));
        contCerrar.setLayout(new java.awt.BorderLayout());

        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickcheck/assets/barra_titulo/icons8-close-20-white.png"))); // NOI18N
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarMouseExited(evt);
            }
        });
        contCerrar.add(lblCerrar, java.awt.BorderLayout.CENTER);

        botonesBarraTitulo.add(contCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 60, 50));

        barraTitulo.add(botonesBarraTitulo, java.awt.BorderLayout.EAST);

        txtTitulo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtTitulo.setText("    Administrador");
        barraTitulo.add(txtTitulo, java.awt.BorderLayout.LINE_START);

        getContentPane().add(barraTitulo, java.awt.BorderLayout.PAGE_START);

        barraLateral.setBackground(new java.awt.Color(56, 33, 165));
        barraLateral.setPreferredSize(new java.awt.Dimension(70, 670));
        barraLateral.setLayout(new java.awt.BorderLayout());

        contBarraLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contBotonBarraLateral.setBackground(new java.awt.Color(56, 33, 165));

        lblBotonBarraLateral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBotonBarraLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickcheck/assets/iconos_barra_lateral/icons8-menu-30-white.png"))); // NOI18N
        lblBotonBarraLateral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBotonBarraLateralMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBotonBarraLateralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBotonBarraLateralMouseExited(evt);
            }
        });

        javax.swing.GroupLayout contBotonBarraLateralLayout = new javax.swing.GroupLayout(contBotonBarraLateral);
        contBotonBarraLateral.setLayout(contBotonBarraLateralLayout);
        contBotonBarraLateralLayout.setHorizontalGroup(
            contBotonBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contBotonBarraLateralLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBotonBarraLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contBotonBarraLateralLayout.setVerticalGroup(
            contBotonBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contBotonBarraLateralLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBotonBarraLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        contBarraLateral.add(contBotonBarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        contConfiguracion.setBackground(new java.awt.Color(56, 33, 165));
        contConfiguracion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblConfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickcheck/assets/iconos_barra_lateral/icons8-settings-30-white.png"))); // NOI18N
        lblConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfiguracionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblConfiguracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConfiguracionMouseExited(evt);
            }
        });
        contConfiguracion.add(lblConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        contBarraLateral.add(contConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 70, 70));

        barraLateral.add(contBarraLateral, java.awt.BorderLayout.NORTH);

        contCerrarSesion.setBackground(new java.awt.Color(56, 33, 165));

        lblCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickcheck/assets/iconos_barra_lateral/icons8-sign-out-30-white.png"))); // NOI18N
        lblCerrarSesion.setPreferredSize(new java.awt.Dimension(70, 70));
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout contCerrarSesionLayout = new javax.swing.GroupLayout(contCerrarSesion);
        contCerrarSesion.setLayout(contCerrarSesionLayout);
        contCerrarSesionLayout.setHorizontalGroup(
            contCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contCerrarSesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contCerrarSesionLayout.setVerticalGroup(
            contCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contCerrarSesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        barraLateral.add(contCerrarSesion, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(barraLateral, java.awt.BorderLayout.LINE_START);

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));

        panelBarraLateral.setBackground(new java.awt.Color(54, 33, 150));
        panelBarraLateral.setOpaque(true);
        panelBarraLateral.setPreferredSize(new java.awt.Dimension(0, 670));

        botonProductos.setBackground(new java.awt.Color(54, 33, 150));
        botonProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonProductosMouseExited(evt);
            }
        });
        botonProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelProductos.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelProductos.setForeground(new java.awt.Color(255, 255, 255));
        labelProductos.setText("Inventario");
        botonProductos.add(labelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 140, 60));

        iconoProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickcheck/assets/iconos_barra_lateral/icons8-inventory-25.png"))); // NOI18N
        botonProductos.add(iconoProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 60));

        panelBarraLateral.add(botonProductos);
        botonProductos.setBounds(0, 0, 210, 60);

        botonUsuarios.setBackground(new java.awt.Color(54, 33, 150));
        botonUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonUsuariosMouseExited(evt);
            }
        });
        botonUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickcheck/assets/iconos_barra_lateral/icons8-user-25.png"))); // NOI18N
        botonUsuarios.add(iconoUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 60));

        labelUsuarios.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        labelUsuarios.setText("Usuarios");
        botonUsuarios.add(labelUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 140, 60));

        panelBarraLateral.add(botonUsuarios);
        botonUsuarios.setBounds(0, 60, 210, 60);

        botonDescuentos.setBackground(new java.awt.Color(54, 33, 150));
        botonDescuentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonDescuentosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonDescuentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonDescuentosMouseExited(evt);
            }
        });
        botonDescuentos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDescuentos.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelDescuentos.setForeground(new java.awt.Color(255, 255, 255));
        labelDescuentos.setText("Descuentos");
        botonDescuentos.add(labelDescuentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 140, 60));

        iconoDescuentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoDescuentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickcheck/assets/iconos_barra_lateral/icons8-discount-25.png"))); // NOI18N
        botonDescuentos.add(iconoDescuentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 60));

        panelBarraLateral.add(botonDescuentos);
        botonDescuentos.setBounds(0, 120, 210, 60);

        botonVentas.setBackground(new java.awt.Color(54, 33, 150));
        botonVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonVentasMouseExited(evt);
            }
        });
        botonVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickcheck/assets/iconos_barra_lateral/icons8-sales-25.png"))); // NOI18N
        botonVentas.add(iconoVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 60));

        labelVentas.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelVentas.setForeground(new java.awt.Color(255, 255, 255));
        labelVentas.setText("Ventas");
        botonVentas.add(labelVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 140, 60));

        panelBarraLateral.add(botonVentas);
        botonVentas.setBounds(0, 180, 210, 60);

        botonInformes.setBackground(new java.awt.Color(54, 33, 150));
        botonInformes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInformesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonInformesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonInformesMouseExited(evt);
            }
        });
        botonInformes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoInformes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoInformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickcheck/assets/iconos_barra_lateral/icons8-report-25.png"))); // NOI18N
        botonInformes.add(iconoInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 60));

        labelInformes.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelInformes.setForeground(new java.awt.Color(255, 255, 255));
        labelInformes.setText("Informes");
        botonInformes.add(labelInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 140, 60));

        panelBarraLateral.add(botonInformes);
        botonInformes.setBounds(0, 240, 210, 60);

        botonCaja.setBackground(new java.awt.Color(54, 33, 150));
        botonCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCajaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCajaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCajaMouseExited(evt);
            }
        });
        botonCaja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCaja.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelCaja.setForeground(new java.awt.Color(255, 255, 255));
        labelCaja.setText("Caja");
        botonCaja.add(labelCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 140, 60));

        iconoCaja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickcheck/assets/iconos_barra_lateral/icons8-checkout-25.png"))); // NOI18N
        botonCaja.add(iconoCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 60));

        panelBarraLateral.add(botonCaja);
        botonCaja.setBounds(0, 300, 210, 60);

        panelMenuPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelMenuPrincipal.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Usa la barra lateral para moverte entre ventanas");

        panelMenuPrincipal.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelMenuPrincipalLayout = new javax.swing.GroupLayout(panelMenuPrincipal);
        panelMenuPrincipal.setLayout(panelMenuPrincipalLayout);
        panelMenuPrincipalLayout.setHorizontalGroup(
            panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuPrincipalLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(151, 151, 151))
        );
        panelMenuPrincipalLayout.setVerticalGroup(
            panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuPrincipalLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addGap(261, 261, 261))
        );

        panelVentas.setBackground(new java.awt.Color(153, 153, 255));
        panelVentas.setOpaque(true);

        javax.swing.GroupLayout panelVentasLayout = new javax.swing.GroupLayout(panelVentas);
        panelVentas.setLayout(panelVentasLayout);
        panelVentasLayout.setHorizontalGroup(
            panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        panelVentasLayout.setVerticalGroup(
            panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        panelProductos.setBackground(new java.awt.Color(0, 255, 255));
        panelProductos.setOpaque(true);

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        panelDescuentos.setBackground(new java.awt.Color(204, 255, 0));
        panelDescuentos.setOpaque(true);

        javax.swing.GroupLayout panelDescuentosLayout = new javax.swing.GroupLayout(panelDescuentos);
        panelDescuentos.setLayout(panelDescuentosLayout);
        panelDescuentosLayout.setHorizontalGroup(
            panelDescuentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        panelDescuentosLayout.setVerticalGroup(
            panelDescuentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        panelUsuarios.setBackground(new java.awt.Color(255, 204, 255));
        panelUsuarios.setOpaque(true);

        javax.swing.GroupLayout panelUsuariosLayout = new javax.swing.GroupLayout(panelUsuarios);
        panelUsuarios.setLayout(panelUsuariosLayout);
        panelUsuariosLayout.setHorizontalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        panelUsuariosLayout.setVerticalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        panelInformes.setBackground(new java.awt.Color(204, 204, 0));
        panelInformes.setOpaque(true);

        javax.swing.GroupLayout panelInformesLayout = new javax.swing.GroupLayout(panelInformes);
        panelInformes.setLayout(panelInformesLayout);
        panelInformesLayout.setHorizontalGroup(
            panelInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        panelInformesLayout.setVerticalGroup(
            panelInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        panelCaja.setBackground(new java.awt.Color(0, 204, 204));
        panelCaja.setOpaque(true);

        javax.swing.GroupLayout panelCajaLayout = new javax.swing.GroupLayout(panelCaja);
        panelCaja.setLayout(panelCajaLayout);
        panelCajaLayout.setHorizontalGroup(
            panelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        panelCajaLayout.setVerticalGroup(
            panelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelVentanaPanelesLayout = new javax.swing.GroupLayout(panelVentanaPaneles);
        panelVentanaPaneles.setLayout(panelVentanaPanelesLayout);
        panelVentanaPanelesLayout.setHorizontalGroup(
            panelVentanaPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
            .addGroup(panelVentanaPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelMenuPrincipal, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(panelVentanaPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelVentas))
            .addGroup(panelVentanaPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelProductos))
            .addGroup(panelVentanaPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelDescuentos, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(panelVentanaPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelUsuarios))
            .addGroup(panelVentanaPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelInformes, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(panelVentanaPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelCaja, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        panelVentanaPanelesLayout.setVerticalGroup(
            panelVentanaPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(panelVentanaPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelMenuPrincipal))
            .addGroup(panelVentanaPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelVentas))
            .addGroup(panelVentanaPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelProductos))
            .addGroup(panelVentanaPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelDescuentos))
            .addGroup(panelVentanaPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelUsuarios))
            .addGroup(panelVentanaPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelInformes))
            .addGroup(panelVentanaPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelCaja, javax.swing.GroupLayout.Alignment.TRAILING))
        );

        javax.swing.GroupLayout panelVentanaLayout = new javax.swing.GroupLayout(panelVentana);
        panelVentana.setLayout(panelVentanaLayout);
        panelVentanaLayout.setHorizontalGroup(
            panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentanaLayout.createSequentialGroup()
                .addComponent(panelBarraLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1210, Short.MAX_VALUE))
            .addGroup(panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelVentanaPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelVentanaLayout.setVerticalGroup(
            panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVentanaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelBarraLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelVentanaPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panelFondo, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Botones de la barra de título">
    
    // Animaciones del botón de cerrar de la barra de título
    private void lblCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseEntered
        contCerrar.setBackground(new Color(255, 40, 86));
    }//GEN-LAST:event_lblCerrarMouseEntered

    private void lblCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseExited
        contCerrar.setBackground(new Color(87,154,233));
    }//GEN-LAST:event_lblCerrarMouseExited
    
   // Animaciones del botón de maximizar de la barra de título 
    private void lblMaximizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaximizarMouseEntered
        contMaximizar.setBackground(new Color(115, 169, 233));
    }//GEN-LAST:event_lblMaximizarMouseEntered

    private void lblMaximizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaximizarMouseExited
        contMaximizar.setBackground(new Color(87,154,233));
    }//GEN-LAST:event_lblMaximizarMouseExited

    // Animaciónes del botón de ocultar de la barra de título
    private void lblOcultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOcultarMouseEntered
        contOcultar.setBackground(new Color(115, 169, 233));
    }//GEN-LAST:event_lblOcultarMouseEntered

    private void lblOcultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOcultarMouseExited
        contOcultar.setBackground(new Color(87,154,233));
    }//GEN-LAST:event_lblOcultarMouseExited

    // Eventos de los botones de la barra de título
    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        mbm.cerrarVentana();
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaximizarMouseClicked
        mbm.maximizarVentana(this);
    }//GEN-LAST:event_lblMaximizarMouseClicked

    private void lblOcultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOcultarMouseClicked
        mbm.ocultarVentana(this);
    }//GEN-LAST:event_lblOcultarMouseClicked
    
    // Eventos para poder arrastrar la ventana usando la barra de título
    private void barraTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraTituloMousePressed
        mouseX =  evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_barraTituloMousePressed

    private void barraTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraTituloMouseDragged
        mbm.arrastrarVentana(this);
        
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_barraTituloMouseDragged

    // Evento para maximizar la ventana haciendo doble click
    private void barraTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraTituloMouseClicked
        mbm.maximizarDobleClick(this);
    }//GEN-LAST:event_barraTituloMouseClicked
    // </editor-fold> 
    
    // <editor-fold defaultstate="collapsed" desc="Barra lateral">
    
    // Animaciones y eventos del botón de configuración de la barra lateral
    private void lblConfiguracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfiguracionMouseExited
        contConfiguracion.setBackground(new Color(56,33,165));
    }//GEN-LAST:event_lblConfiguracionMouseExited

    private void lblConfiguracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfiguracionMouseEntered
        contConfiguracion.setBackground(new Color(75, 50, 188));
    }//GEN-LAST:event_lblConfiguracionMouseEntered
    
    private void lblConfiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfiguracionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblConfiguracionMouseClicked

    // Animaciones y eventos del botón para alternar la visibilidad de la barra lateral
    private void lblBotonBarraLateralMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotonBarraLateralMouseExited
        contBotonBarraLateral.setBackground(new Color(56,33,165));
    }//GEN-LAST:event_lblBotonBarraLateralMouseExited

    private void lblBotonBarraLateralMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotonBarraLateralMouseEntered
        contBotonBarraLateral.setBackground(new Color(75, 50, 188));
    }//GEN-LAST:event_lblBotonBarraLateralMouseEntered
    
    private void lblBotonBarraLateralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotonBarraLateralMouseClicked
        mbl.alternarBarraLateral(panelBarraLateral, lblBotonBarraLateral);
    }//GEN-LAST:event_lblBotonBarraLateralMouseClicked
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Botones de la barra lateral">
    
// Animaciones y eventos de la opción 'Caja' de la barra lateral.
    private void botonCajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCajaMouseExited
        botonCaja.setBackground(new Color(54,33,150));
    }//GEN-LAST:event_botonCajaMouseExited

    private void botonCajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCajaMouseEntered
        botonCaja.setBackground(new Color(75, 50, 188));
    }//GEN-LAST:event_botonCajaMouseEntered

    private void botonCajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCajaMouseClicked
        mbl.cambiarPanel(panelVentanaPaneles, panelCaja);
        mbl.alternarBarraLateral(panelBarraLateral, lblBotonBarraLateral);
    }//GEN-LAST:event_botonCajaMouseClicked

    // Animaciones y eventos de la opción 'Informes' de la barra lateral.
    private void botonInformesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInformesMouseExited
        botonInformes.setBackground(new Color(54,33,150));
    }//GEN-LAST:event_botonInformesMouseExited

    private void botonInformesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInformesMouseEntered
        botonInformes.setBackground(new Color(75, 50, 188));
    }//GEN-LAST:event_botonInformesMouseEntered

    private void botonInformesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInformesMouseClicked
        mbl.cambiarPanel(panelVentanaPaneles, panelInformes);
        mbl.alternarBarraLateral(panelBarraLateral, lblBotonBarraLateral);
    }//GEN-LAST:event_botonInformesMouseClicked

    // Animaciones y eventos de la opción 'Ventas' de la barra lateral.
    private void botonVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVentasMouseExited
        botonVentas.setBackground(new Color(54,33,150));
    }//GEN-LAST:event_botonVentasMouseExited

    private void botonVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVentasMouseEntered
        botonVentas.setBackground(new Color(75, 50, 188));
    }//GEN-LAST:event_botonVentasMouseEntered

    private void botonVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVentasMouseClicked
        mbl.cambiarPanel(panelVentanaPaneles, panelVentas);
        mbl.alternarBarraLateral(panelBarraLateral, lblBotonBarraLateral);
    }//GEN-LAST:event_botonVentasMouseClicked

    // Animaciones y eventos de la opción 'Descuentos' de la barra lateral.
    private void botonDescuentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDescuentosMouseExited
        botonDescuentos.setBackground(new Color(54,33,150));
    }//GEN-LAST:event_botonDescuentosMouseExited

    private void botonDescuentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDescuentosMouseEntered
        botonDescuentos.setBackground(new Color(75, 50, 188));
    }//GEN-LAST:event_botonDescuentosMouseEntered

    private void botonDescuentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDescuentosMouseClicked
        mbl.cambiarPanel(panelVentanaPaneles, panelDescuentos);
        mbl.alternarBarraLateral(panelBarraLateral, lblBotonBarraLateral);
    }//GEN-LAST:event_botonDescuentosMouseClicked

    // Animaciones y eventos de la opción 'Usuarios' de la barra lateral.
    private void botonUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonUsuariosMouseExited
        botonUsuarios.setBackground(new Color(54,33,150));
    }//GEN-LAST:event_botonUsuariosMouseExited

    private void botonUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonUsuariosMouseEntered
        botonUsuarios.setBackground(new Color(75, 50, 188));
    }//GEN-LAST:event_botonUsuariosMouseEntered

    private void botonUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonUsuariosMouseClicked
        mbl.cambiarPanel(panelVentanaPaneles, panelUsuarios);
        mbl.alternarBarraLateral(panelBarraLateral, lblBotonBarraLateral);
    }//GEN-LAST:event_botonUsuariosMouseClicked

    // Animaciones y eventos de la opción 'Productos' de la barra lateral.
    private void botonProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonProductosMouseExited
        botonProductos.setBackground(new Color(54,33,150));
    }//GEN-LAST:event_botonProductosMouseExited

    private void botonProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonProductosMouseEntered
        botonProductos.setBackground(new Color(75, 50, 188));
    }//GEN-LAST:event_botonProductosMouseEntered

    private void botonProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonProductosMouseClicked
        mbl.cambiarPanel(panelVentanaPaneles, panelProductos);
        mbl.alternarBarraLateral(panelBarraLateral, lblBotonBarraLateral);
    }//GEN-LAST:event_botonProductosMouseClicked
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Animaciones y eventos del botón de cerrar sesión">
    private void lblCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseEntered
        contCerrarSesion.setBackground(new Color(75, 50, 188));
    }//GEN-LAST:event_lblCerrarSesionMouseEntered

    private void lblCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseExited
        contCerrarSesion.setBackground(new Color(56,33,165));
    }//GEN-LAST:event_lblCerrarSesionMouseExited

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        LoginForm loginForm = new LoginForm(cn);
        loginForm.setVisible(true);
        loginForm.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_lblCerrarSesionMouseClicked
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Declaracion de variables de los componentes">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraLateral;
    private javax.swing.JPanel barraTitulo;
    private javax.swing.JPanel botonCaja;
    private javax.swing.JPanel botonDescuentos;
    private javax.swing.JPanel botonInformes;
    private javax.swing.JPanel botonProductos;
    private javax.swing.JPanel botonUsuarios;
    private javax.swing.JPanel botonVentas;
    private javax.swing.JPanel botonesBarraTitulo;
    private javax.swing.JPanel contBarraLateral;
    private javax.swing.JPanel contBotonBarraLateral;
    private javax.swing.JPanel contCerrar;
    private javax.swing.JPanel contCerrarSesion;
    private javax.swing.JPanel contConfiguracion;
    private javax.swing.JPanel contMaximizar;
    private javax.swing.JPanel contOcultar;
    private javax.swing.JLabel iconoCaja;
    private javax.swing.JLabel iconoDescuentos;
    private javax.swing.JLabel iconoInformes;
    private javax.swing.JLabel iconoProductos;
    private javax.swing.JLabel iconoUsuarios;
    private javax.swing.JLabel iconoVentas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelCaja;
    private javax.swing.JLabel labelDescuentos;
    private javax.swing.JLabel labelInformes;
    private javax.swing.JLabel labelProductos;
    private javax.swing.JLabel labelUsuarios;
    private javax.swing.JLabel labelVentas;
    private javax.swing.JLabel lblBotonBarraLateral;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblConfiguracion;
    private javax.swing.JLabel lblMaximizar;
    private javax.swing.JLabel lblOcultar;
    private javax.swing.JLayeredPane panelBarraLateral;
    private javax.swing.JLayeredPane panelCaja;
    private javax.swing.JLayeredPane panelDescuentos;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JLayeredPane panelInformes;
    private javax.swing.JLayeredPane panelMenuPrincipal;
    private javax.swing.JLayeredPane panelProductos;
    private javax.swing.JLayeredPane panelUsuarios;
    private javax.swing.JPanel panelVentana;
    private javax.swing.JPanel panelVentanaPaneles;
    private javax.swing.JLayeredPane panelVentas;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
}
